// Canonical ESLint flat config, replicated from the engine (STACK.md §2).
// `./.nuxt/eslint.config.mjs` is generated by `nuxt prepare` (the lint script
// runs it first); the @nuxt/eslint module itself is inherited from the engine
// layer, but the package must live in THIS repo's devDependencies (STACK §5.10
// — remote-layer installs are prod-deps-only, so layer modules resolve from
// the consumer's node_modules). eslint-config-prettier is appended LAST so any
// stylistic rule that would fight Prettier is disabled — Prettier owns
// formatting, ESLint owns correctness.
import eslintConfigPrettier from 'eslint-config-prettier/flat';

import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(
  // Pipeline artifacts, local caches, and design references (design/ is
  // reference material, not app code).
  {
    ignores: ['raw/**', 'cache/**', 'public/data/**', 'data/**', 'design/**'],
  },
  eslintConfigPrettier,
);
